# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 571bb1222c0bb82fada66fee57f9ac8557db339392f7ba8073b9a9713985b0f6b449f6af2a97b0abbb864957c28ff256bea00ccac1a3566f8f3e3a790f872ed3

test:
  secret_key_base: 131aa58da6939d2faeae87546478d70ef37dbf15f56ba536166a46906ac6aa82198fc8d3d664a3b991cd6c7a5024339d37eac879e9323f1af06bb1d77f63b3a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
